version: "3"

services:
  db:
    container_name: ${APP_NAME}_pgdb
    restart: always
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - 5432:${DB_PORT}
    volumes:
      - db-store:/var/lib/postgresql/data
  app:
    container_name: ${APP_NAME}_app
    build: .
    command: python manage.py runserver 0.0.0.0:${APP_PORT}
    volumes:
      - .:/app/backend
    ports:
      - 8888:${APP_PORT}
    depends_on:
      - db

volumes:
  db-store:
